#!/bin/bash -l
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem=1G
#SBATCH --time=72:00:00
#SBATCH --mail-user=sagane.joye@unil.ch
#SBATCH --error=snakemake.err

conda activate snakemake_2

cd /work/FAC/FBM/DEE/rwaterho/evofun/sagane/asm_snakemake/ScoCin_v1/workflow_decontam

snakemake --profile slurm --use-conda --unlock
snakemake --profile slurm --use-conda --rerun-incomplete

